pub mod constants;
pub mod error;
pub mod instructions;
pub mod state;

use anchor_lang::prelude::*;

// pub use (not just `use`) so that __client_accounts_* macros generated by
// #[derive(Accounts)] are accessible at the crate root, which Anchor requires.
pub use instructions::*;
pub use state::*;
pub use error::*;

declare_id!("4yR7v2c23wrxgFzcbtocvMvVxucYQHGfSWczNW3FxV7T");

// NOTE: module is named `lattice`, NOT `program` — using `program` conflicts
// with `solana_program::program` that anchor's prelude brings into scope.
#[program]
pub mod lattice {
    use super::*;

    pub fn register_provider(
        ctx: Context<RegisterProvider>,
        qvac_pubkey: [u8; 32],
        models: Vec<[u8; 32]>,
        price_per_1k: u64,
        stake_amount: u64,
    ) -> Result<()> {
        instructions::register_provider::handler(ctx, qvac_pubkey, models, price_per_1k, stake_amount)
    }

    pub fn deregister_provider(ctx: Context<DeregisterProvider>) -> Result<()> {
        instructions::deregister_provider::handler(ctx)
    }

    pub fn update_provider(
        ctx: Context<UpdateProvider>,
        qvac_pubkey: [u8; 32],
        models: Vec<[u8; 32]>,
        price_per_1k: u64,
    ) -> Result<()> {
        instructions::update_provider::handler(ctx, qvac_pubkey, models, price_per_1k)
    }

    pub fn lock_job(
        ctx: Context<LockJob>,
        job_id: [u8; 32],
        amount: u64,
    ) -> Result<()> {
        instructions::lock_job::handler(ctx, job_id, amount)
    }

    pub fn settle_job(
        ctx: Context<SettleJob>,
        job_id: [u8; 32],
        result_hash: [u8; 32],
    ) -> Result<()> {
        instructions::settle_job::handler(ctx, job_id, result_hash)
    }

    pub fn slash_provider(
        ctx: Context<SlashProvider>,
        job_id: [u8; 32],
    ) -> Result<()> {
        instructions::slash_provider::handler(ctx, job_id)
    }
}
