[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lattice = "CgZjVR1SqQFn6SQfSpxVd7hTGR7HQix3cCHuWS8SnQiH"

[programs.devnet]
lattice = "CgZjVR1SqQFn6SQfSpxVd7hTGR7HQix3cCHuWS8SnQiH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
