[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
lattice = "4yR7v2c23wrxgFzcbtocvMvVxucYQHGfSWczNW3FxV7T"

[programs.localnet]
lattice = "4yR7v2c23wrxgFzcbtocvMvVxucYQHGfSWczNW3FxV7T"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
